name: Get Default Branch Commit Hash

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Default Branch Commit Hash
        id: commit_hash
        run: git log
