name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  geckow:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo ref"
        run: echo ${{ github.ref == github.event.repository.default_branch }}
