name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  geckow:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo ref"
        run: echo ${{ github.ref }} && echo ${{ github.event.repository.default_branch }}

  gh2:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo github ctx"
        run: echo ${{ toJson(github.event.repository) }}

