name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  geckow:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo ref"
        run: echo ${{ github.ref }} && echo ${{ github.event.repository.default_branch }}

      - name: "Echo github"
        run: echo ${{ toJSON(github) }}
